### ISSUE TITLE
KeyError: 'Tr'

### ISSUE THREAD

**Issue by crankler** [amslabtech/semantickitti2bag#2]
Hi, thank you for your share code.
When I input:  python __main__.py -p ../  -s 00
there show:
>    File "../semantic_kitti/semantickitti2bag-master/semantickitti2bag.py", line 231, in read_poses_file
>    Tr = calibration["Tr"]
> KeyError: 'Tr'

Can you tell me how to fix it, thank you!

**Comment by crankler** [comment]
I've solved it!

**Comment by bconstantine** [comment]
For those who are wondering the fix, make sure to download the calib.txt from this link https://www.cvlibs.net/datasets/kitti/eval_odometry.php
not the other one
