### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/root/data/dataset/sequences/00/00.txt'

### ISSUE THREAD

**Issue by creatorofuniverses** [amslabtech/semantickitti2bag#3]
An error occurred when opening the gt file.

I found this code in semantickitti2bag.py (lines 534 and 535):
```
ground_truth_file_name = "{}.txt".format(args.sequence_number)
ground_truth = read_poses_file(os.path.join(kitti.data_path, ground_truth_file_name), calibration)
```

But gt_file is called "poses.txt"
So, I replaced line 534 with this:
`ground_truth_file_name =  "poses.txt"`

And everything works.

**Comment by jo-jstrm** [comment]
Thanks for leaving that here
